export const GET_TAREFAS = 'GET_TAREFAS';
export const SELECT_TAREFA = 'SELECT_TAREFA';
export const TAREFAS_RECEIVED = 'TAREFAS_RECEIVED';
export const SEND_TAREFA_DATA = 'SEND_TAREFA_DATA';
export const LOADING_TAREFA = 'LOADING_TAREFA';
